config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about", as: "about"

  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      get 'daily_search' => 'users#daily_search'
  end

  get 'search' => 'searches#search'

  resources :chats, only: [:show, :create]

  resources :groups, only: [:new, :index, :show, :create, :edit, :update] do
    resource :group_users, only: [:create, :destroy]
  end

    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    @comment = current_user.book_comments.new(book_comment_params)
    @comment.book_id = book.id
    @comment.save
    #redirect_to request.referer
    render :index
  end

  def destroy
    @comment = BookComment.find(params[:id])
    @comment.destroy
    #redirect_to request.referer
    render :index
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_count.html.erb
コメント数: <%= book.book_comments.count %>

app/views/book_comments/_form.html.erb
<%= form_with model: [book, book_comment], local: false do |f| %>
   <%= f.text_area :comment, class: "form-control" %>
   <%= f.submit "送信" %>
<% end %>

app/views/book_comments/_index.html.erb
<table>
  <% book.book_comments.each do |book_comment| %>
  <tr>
    <td>
      <%= link_to user_path(book_comment.user_id) do %>
        <%= image_tag book_comment.user.get_profile_image(100,100) %></br>
        <%= book_comment.user.name %>
      <% end %>
    </td>
    <td><%= book_comment.comment %></td>
    <td>
      <% if book_comment.user == current_user %>
        <%= link_to 'Destroy', book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class: "btn btn-danger" %>
      <% end %>
    </td>
  </tr>
  <% end %>
</table>

app/views/book_comments/index.js.erb
$('.comments-count').html("<%= j(render 'book_comments/count', book: @comment.book) %>")
$('.comments-area').html("<%= j(render 'book_comments/index', book: @comment.book ) %>")
$('textarea').val("")