config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about", as: "about"

  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      get 'daily_search' => 'users#daily_search'
  end

  get 'search' => 'searches#search'

  resources :chats, only: [:show, :create]

  resources :groups, only: [:new, :index, :show, :create, :edit, :update] do
    resource :group_users, only: [:create, :destroy]
  end

    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  has_one_attached :image
  belongs_to :owner, class_name: 'User'
  has_many :group_users, dependent: :destroy

  validates :name, presence: true
  validates :introduction, presence: true

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def is_owned_by?(user)
    owner.id == user.id
  end

  def includesUser?(user)
    group_users.exists?(user_id: user.id)
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def new
    @group = Group.new
  end

  def index
    @book = Book.new
    @groups = Group.all
  end

  def show
    @book = Book.new
    @group = Group.find(params[:id])
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    if @group.save
      redirect_to groups_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to groups_path
    else
      render :edit
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction, :image)
  end

  def is_matching_login_user
    @group = Group.find(params[:id])
    unless @group.owner_id == current_user.id
      redirect_to groups_path
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with model:group do |f| %>

  <div class="form-group">
    <label for="group_name">グループ名</label>
    <div>
      <%= f.text_field :name, class: "form_control" %>
    </div>
  </div>

  <div class="form-group">
    <label for="group_introduction">紹介文</label>
    <div>
      <%= f.text_area :introduction, class: "form_control" %>
    </div>
  </div>

  <div class="form-group">
    <label for="group_image">グループ画像</label>
    <div>
      <%= f.file_field :image, accept: "image/*" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.submit 'Create Group', class: "btn btn-info" %>
  </div>

<% end %>

app/views/groups/_index.html.erb
<table class="table">

  <thead>
    <tr>
      <th></th>
      <th>グループ名</th>
      <th>紹介文</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% groups.each do |group| %>
      <tr>
        <td><%= image_tag group.get_image(50,50) %></td>
        <td><%= link_to group.name, group_path(group.id) %></td>
        <td><%= group.introduction %></td>
        <td><!--%= group.users.count %--></td>
        <td>
          <% if group.is_owned_by?(current_user) %>
            <%= link_to 'Edit', edit_group_path(group.id), class: "btn btn-success" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/groups/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-o mx-auto">
      <h1>Editing Group</h1>
        <%= render 'layouts/error', obj: @group %>
        <%= render 'form', group: @group %>
      </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
        <%= render 'users/info', user: current_user %>
      <h2 class-"mt-3">New book</h2>
        <%= render 'books/form', book: @book %> 
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Groups</h2>
      <%= render 'index', groups: @groups %>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-o mx-auto">
      <h1>Create Group</h1>
        <%= render 'layouts/error', obj: @group %>
        <%= render 'form', group: @group %>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Group Detail</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= image_tag @group.get_image(50,50) %></td>
            <td><%= @group.name %></td>
            <td><%= @group.introduction %></td>
            <td>
              <% @group.users.each do |user| %>
                <li style="list-style: none;"><%= user.name %></li>
              <% end %>
            </td>
            <td>
              <% if @group.is_owned_by?(current_user) %>
                <%= link_to 'Edit', edit_group_path(@group.id), class: "btn btn-sm btn-success" %>
              <% elsif @group.includesUser?(current_user)%>
                <%= link_to 'Leave this group', group_path(@group.id), method: :delete, class: "btn btn-sm btn-danger" %>
              <% else %>
                <%= link_to 'Join this group', group_join_path(@group.id), class: "btn btn-sm btn-success" %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

  </div>
</div>